version: "2.0"
services:
  database:
    image: sameersbn/postgresql:9.5-2
    restart: always
    environment:
      - DEBUG=false
      - DB_USER
      - DB_PASS
      - DB_NAME
    volumes:
      - ./postgresql:/var/lib/postgresql
  website:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile.web
    environment:
      - SERVER_PORT=3000
      - DB_USER
      - DB_PASSWD
      - DB_NAME
      - DB_HOST
      - DB_PORT=5432
      - ENVIRONMENT
    links:
      - database
    depends_on:
      - database
    tty: false
    ports:
      - "3000:3000"
    working_dir: /opt/server
  nginx:
    build:
      context: ./
      dockerfile: ./deployment/Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - website
    depends_on:
      - website
