FROM ubuntu:16.04
MAINTAINER Erik Aker

RUN ["apt-get", "update", "-y"]
RUN ["apt-get", "install", "-y", "libpq-dev", "netcat-traditional", "netbase"]

RUN mkdir -p /opt/server

COPY ./assets /opt/server/assets/
COPY ./client /opt/server/client/
COPY ./build/simpleservantblog-exe /opt/server/simpleservantblog-exe

WORKDIR /opt/server

# We have to throw in this hack to make sure underlying services are ready
# before we try to start this thing. Docker-compose may fix this someday?
RUN echo "#!/bin/bash" > runner.sh \
  && echo "while ! nc -w 5 -z database 5432; do sleep 0.1; done" >> runner.sh \
  && echo "/opt/server/simpleservantblog-exe" >> runner.sh \
  && chmod +x runner.sh


EXPOSE 3000
ENTRYPOINT ["./runner.sh"]
